export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
    <meta charset="utf-8">
    <title>EuclideanTSPSolver</title>
    <base href="/Euclidean-TSP-Solver/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.centered-rectangle{width:min(80vw,1000px);height:min(80vh,400px);background-color:#f0f0f0;border:2px solid #333;border-radius:8px;display:flex;flex-direction:column;justify-content:center;align-items:center;padding:20px;position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}.centered-rectangle p{font-size:20px;color:#333}.click-area{width:100%;height:100%;border:2px dashed #ccc;display:flex;flex-direction:column;justify-content:center;align-items:center}.enabled-area{cursor:pointer}.disabled-area{cursor:not-allowed}.coordinates{margin-top:20px;padding:10px;background-color:#f0f0f0;border-radius:4px}.circle{position:absolute;width:10px;height:10px;border-radius:50%;background-color:red;transform:translate(-50%,-50%);transform-origin:center;z-index:2;transition:transform .3s ease,box-shadow .3s ease}.circle:hover{transform:translate(-50%,-50%) scale(1.2);box-shadow:0 0 10px #ff000080}.circle.first-vertex{background-color:#ff9f43;width:16px;height:16px;box-shadow:0 0 0 3px #ff9f434d}.circle.first-vertex:hover{transform:translate(-50%,-50%) scale(1.3);box-shadow:0 0 15px #ff9f4380}.calculate,.clear{margin-top:20px;padding:10px;background-color:#e0e0e0;border-radius:4px;cursor:pointer;transition:background-color .3s ease,transform .2s ease}.calculate:not(:disabled):hover,.clear:not(:disabled):hover{background-color:#007bff;color:#fff;transform:scale(1.1)}.path-svg{position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none;z-index:1}.button-row{display:flex;justify-content:center;gap:16px;margin-top:12px;padding:8px}@keyframes drawPath{0%{stroke-dasharray:0,100%}to{stroke-dasharray:100%,0}}.animate-path{stroke-dasharray:0,100%;animation:drawPath 2s ease-out forwards}.preview-vertex{position:absolute;width:10px;height:10px;border-radius:50%;background-color:#ff000080;transform:translate(-50%,-50%);pointer-events:none;z-index:3}button:disabled{background-color:#a0a0a0;cursor:not-allowed;transform:none}
</style></head>
  <body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
    <app-root ng-version="20.0.2" ngh="1" ng-server-context="ssg"><app-centered-box ngh="0"><div class="centered-rectangle"><div class="click-area enabled-area" jsaction="click:;"><p> Click anywhere inside this area to place vertices </p><!----><p>Click on a vertex to remove it</p><!----></div><div class="button-row"><button class="clear" jsaction="click:;"> Clear </button><button class="calculate" jsaction="click:;"> Calculate </button></div></div><!----><!----><svg class="path-svg"><!----></svg></app-centered-box><router-outlet></router-outlet><!----></app-root>
  <script src="polyfills-SCHOHYNV.js" type="module"></script><script src="main-WZNO2UFS.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"2":"t0","3":"t1","9":"t2","10":"t3","12":"t4"},"c":{"2":[{"i":"t0","r":1}],"3":[{"i":"t1","r":1}],"9":[],"10":[],"12":[]}},{"c":{"1":[]}}]}</script></body></html>`;