name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install angular cli
        run: npm install -g @angular/cli

      - name: Install ghpages for angular cli
        run: npm install angular-cli-ghpages --save-dev

      - name: Build Angular app
        run: ng build --configuration production --base-href /Euclidean-TSP-Solver/

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ng deploy --base-href=/Euclidean-TSP-Solver/
        # test
